---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  become: yes
  become_method: sudo
  vars:
    str1: "{{word1}}"
    str2: "{{word2}}"
  tasks:
    - name: Build Docker Image
      docker_image:
        build:
          path: .
        name: anagram-image
        source: build
        state: present
        force: 1

    - name: Run Command inside Anagram-Image Container
      docker_container:
        name: anagram-image
        image: anagram-image
        command: ["python3","anagram-py.py", "{{str1}}", "{{str2}}"]
        detach: yes
      register: result_of_action











    



    